### PR TITLE
Add dev step - assume user does not have grunt

### PR DESCRIPTION
**Pull request by hubdotcom**
As in Setup steps -  assume user does not have grunt installed

### CODE REVIEW

**Comment by MartinKolarik** [comment]
Global grunt wasn't really needed, I updated the README to use `npm run start` instead.

**Comment by hubdotcom** [comment]
Great! running `npm run start` I get this:

```Done, without errors.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Server.listen (net.js:1240:5)
    at EventEmitter.app.listen (/beta.jsdelivr.com/node_modules/express/lib/application.js:559:24)
    at Object.<anonymous> (/beta.jsdelivr.com/app/app.js:65:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

npm-debug.log
```0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart beta-jsdelivr-com@0.1.0
6 info start beta-jsdelivr-com@0.1.0
7 verbose unsafe-perm in lifecycle true
8 info beta-jsdelivr-com@0.1.0 Failed to exec start script
9 verbose stack Error: beta-jsdelivr-com@0.1.0 start: `grunt && node app/app.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid beta-jsdelivr-com@0.1.0
11 verbose cwd /Users/Jamie/beta.jsdelivr.com
12 error Darwin 14.3.0
13 error argv "node" "/usr/local/bin/npm" "run" "start"
14 error node v0.12.1
15 error npm  v2.5.1
16 error code ELIFECYCLE
17 error beta-jsdelivr-com@0.1.0 start: `grunt && node app/app.js`
17 error Exit status 1
18 error Failed at the beta-jsdelivr-com@0.1.0 start script 'grunt && node app/app.js'.
18 error This is most likely a problem with the beta-jsdelivr-com package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     grunt && node app/app.js
18 error You can get their info via:
18 error     npm owner ls beta-jsdelivr-com
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
 ```

**Comment by MartinKolarik** [comment]
EADDRINUSE means there's another process listening on the same port (4400). Maybe it's already running? You can use `npm run build` to rebuild without starting a new web server.

**Comment by hubdotcom** [comment]
Thanks Martin

**Pull request closed without merging**
